// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5IvtCn3eWbVyjafsoh-a_-08Jk7EPfJk',
    appId: '1:242474237761:web:0e9f8f8a83eabf1cb66bc0',
    messagingSenderId: '242474237761',
    projectId: 'foodappsforproject',
    authDomain: 'foodappsforproject.firebaseapp.com',
    databaseURL: 'https://foodappsforproject-default-rtdb.firebaseio.com',
    storageBucket: 'foodappsforproject.appspot.com',
    measurementId: 'G-D210EVVN9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSB6V5YG4wMjERbcNaw7OjLP5BRzhsCE',
    appId: '1:242474237761:android:963cde39c40c74a8b66bc0',
    messagingSenderId: '242474237761',
    projectId: 'foodappsforproject',
    databaseURL: 'https://foodappsforproject-default-rtdb.firebaseio.com',
    storageBucket: 'foodappsforproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hqN2oHF4q-PXRpJhq8AdNXkUpozyuAM',
    appId: '1:242474237761:ios:2a5ccfdbfaf2012fb66bc0',
    messagingSenderId: '242474237761',
    projectId: 'foodappsforproject',
    databaseURL: 'https://foodappsforproject-default-rtdb.firebaseio.com',
    storageBucket: 'foodappsforproject.appspot.com',
    iosClientId: '242474237761-3lm1kot6lor95d8dcob09lp9a595er6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.baisnab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hqN2oHF4q-PXRpJhq8AdNXkUpozyuAM',
    appId: '1:242474237761:ios:9cd1c134da9e0fb0b66bc0',
    messagingSenderId: '242474237761',
    projectId: 'foodappsforproject',
    databaseURL: 'https://foodappsforproject-default-rtdb.firebaseio.com',
    storageBucket: 'foodappsforproject.appspot.com',
    iosClientId: '242474237761-42l4bkclso2p284dv1f80oeai9gio8n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.baisnab.RunnerTests',
  );
}
